### ISSUE TITLE
🚨 Tests:  Write tests for fedrec/communications/messages.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/RecoEdge#104]
### 🛩 Where?

[Here](https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/communications/messages.py)

### 💭 Description

We expect this file to be covered completely by tests. It's not intended to test feature-related functionality but is instead intended to test the file in isolation.

### Type of Test

Unit test

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by Yash-Vardhan-Sharma** [comment]
I can work on it
