### ISSUE TITLE
📚 Documentation: Write inline documentation for fedrec/utilities/registry.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/RecoEdge#60]
# Where?

[Here](https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/utilities/registry.py)

# Who?

Anyone who wants to get know the code base of NimbleEdge as well as any file in the project.

# What?

Please follow these guidelines: [Link](https://numpydoc.readthedocs.io/en/latest/format.html)
We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

# Additional Content 

None

**Comment by oyetripathi** [comment]
I would like to take this up.
