### ISSUE TITLE
📚 Documentation: Write Inline Documentation for train.py

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/RecoEdge#93]
###  🙋 Where

[Here](https://github.com/NimbleEdge/RecoEdge/blob/main/train.py)

### 💭 Description

We need to go "line-by-line" and create inline documentation for this file. Please try to use proper punctuation and English grammar to the best of your ability.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the [guidlines](https://numpydoc.readthedocs.io/en/latest/format.html)?

- [X] I have read the Guildlines

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by Viditagarwal7479** [comment]
I have written the inline documentation for train.py and have created a pull request regarding this issue with the title "Added Inline Documentation".

**Comment by ramesht007** [comment]
Thanks for taking interest !!
Assigned the issue to you.

**Comment by Viditagarwal7479** [comment]
Shouldn't this issue be closed now?
